# ELK stack for Virtual-Vehicles Dockerfile

FROM willdurand/elk:latest

MAINTAINER Bilel I <bilel.brahim@gmail.com>

ENV REFRESHED_AT 2016-11-06

COPY logstash-logspout-log4j2.conf /etc/logstash/logstash-logspout-log4j2.conf
